/**
 * Curated emoji dataset for shopping list app.
 * Food & Drink is the largest category since this is a shopping app.
 */
export const EMOJI_DATA = [
  // Food & Drink (~90 emojis)
  { emoji: '🍎', name: 'red apple', category: 'food' },
  { emoji: '🍏', name: 'green apple', category: 'food' },
  { emoji: '🍐', name: 'pear', category: 'food' },
  { emoji: '🍊', name: 'tangerine orange', category: 'food' },
  { emoji: '🍋', name: 'lemon', category: 'food' },
  { emoji: '🍌', name: 'banana', category: 'food' },
  { emoji: '🍉', name: 'watermelon', category: 'food' },
  { emoji: '🍇', name: 'grapes', category: 'food' },
  { emoji: '🍓', name: 'strawberry', category: 'food' },
  { emoji: '🫐', name: 'blueberries', category: 'food' },
  { emoji: '🍈', name: 'melon cantaloupe', category: 'food' },
  { emoji: '🍒', name: 'cherries', category: 'food' },
  { emoji: '🍑', name: 'peach', category: 'food' },
  { emoji: '🥭', name: 'mango', category: 'food' },
  { emoji: '🍍', name: 'pineapple', category: 'food' },
  { emoji: '🥥', name: 'coconut', category: 'food' },
  { emoji: '🥝', name: 'kiwi fruit', category: 'food' },
  { emoji: '🍅', name: 'tomato', category: 'food' },
  { emoji: '🍆', name: 'eggplant aubergine', category: 'food' },
  { emoji: '🥑', name: 'avocado', category: 'food' },
  { emoji: '🥦', name: 'broccoli', category: 'food' },
  { emoji: '🥬', name: 'leafy green lettuce', category: 'food' },
  { emoji: '🥒', name: 'cucumber', category: 'food' },
  { emoji: '🌶️', name: 'hot pepper chili', category: 'food' },
  { emoji: '🫑', name: 'bell pepper', category: 'food' },
  { emoji: '🌽', name: 'corn', category: 'food' },
  { emoji: '🥕', name: 'carrot', category: 'food' },
  { emoji: '🧄', name: 'garlic', category: 'food' },
  { emoji: '🧅', name: 'onion', category: 'food' },
  { emoji: '🥔', name: 'potato', category: 'food' },
  { emoji: '🍠', name: 'sweet potato', category: 'food' },
  { emoji: '🫘', name: 'beans', category: 'food' },
  { emoji: '🥜', name: 'peanuts', category: 'food' },
  { emoji: '🫛', name: 'pea pod', category: 'food' },
  { emoji: '🍞', name: 'bread', category: 'food' },
  { emoji: '🥖', name: 'baguette french bread', category: 'food' },
  { emoji: '🥨', name: 'pretzel', category: 'food' },
  { emoji: '🧀', name: 'cheese', category: 'food' },
  { emoji: '🥚', name: 'egg', category: 'food' },
  { emoji: '🍳', name: 'fried egg cooking', category: 'food' },
  { emoji: '🥓', name: 'bacon', category: 'food' },
  { emoji: '🥩', name: 'steak meat', category: 'food' },
  { emoji: '🍗', name: 'chicken leg poultry', category: 'food' },
  { emoji: '🍖', name: 'meat bone', category: 'food' },
  { emoji: '🌭', name: 'hot dog', category: 'food' },
  { emoji: '🍔', name: 'hamburger burger', category: 'food' },
  { emoji: '🍟', name: 'french fries', category: 'food' },
  { emoji: '🍕', name: 'pizza', category: 'food' },
  { emoji: '🥗', name: 'salad', category: 'food' },
  { emoji: '🥪', name: 'sandwich', category: 'food' },
  { emoji: '🌮', name: 'taco', category: 'food' },
  { emoji: '🌯', name: 'burrito wrap', category: 'food' },
  { emoji: '🫔', name: 'tamale', category: 'food' },
  { emoji: '🥙', name: 'pita stuffed', category: 'food' },
  { emoji: '🧆', name: 'falafel', category: 'food' },
  { emoji: '🍜', name: 'noodles ramen', category: 'food' },
  { emoji: '🍝', name: 'spaghetti pasta', category: 'food' },
  { emoji: '🍲', name: 'pot food stew', category: 'food' },
  { emoji: '🍛', name: 'curry rice', category: 'food' },
  { emoji: '🍣', name: 'sushi', category: 'food' },
  { emoji: '🍱', name: 'bento box', category: 'food' },
  { emoji: '🥟', name: 'dumpling', category: 'food' },
  { emoji: '🦐', name: 'shrimp prawn', category: 'food' },
  { emoji: '🦞', name: 'lobster', category: 'food' },
  { emoji: '🦀', name: 'crab', category: 'food' },
  { emoji: '🐟', name: 'fish', category: 'food' },
  { emoji: '🍤', name: 'fried shrimp', category: 'food' },
  { emoji: '🧈', name: 'butter', category: 'food' },
  { emoji: '🍯', name: 'honey', category: 'food' },
  { emoji: '🥛', name: 'milk glass', category: 'food' },
  { emoji: '🧃', name: 'juice box', category: 'food' },
  { emoji: '☕', name: 'coffee hot', category: 'food' },
  { emoji: '🍵', name: 'tea', category: 'food' },
  { emoji: '🧉', name: 'mate', category: 'food' },
  { emoji: '🥤', name: 'cup straw soda', category: 'food' },
  { emoji: '🧋', name: 'bubble tea boba', category: 'food' },
  { emoji: '🍺', name: 'beer', category: 'food' },
  { emoji: '🍷', name: 'wine', category: 'food' },
  { emoji: '🥂', name: 'champagne', category: 'food' },
  { emoji: '🍾', name: 'bottle champagne', category: 'food' },
  { emoji: '🧊', name: 'ice cube', category: 'food' },
  { emoji: '🍦', name: 'ice cream', category: 'food' },
  { emoji: '🍨', name: 'ice cream sundae', category: 'food' },
  { emoji: '🍩', name: 'donut doughnut', category: 'food' },
  { emoji: '🍪', name: 'cookie', category: 'food' },
  { emoji: '🎂', name: 'birthday cake', category: 'food' },
  { emoji: '🍰', name: 'cake slice', category: 'food' },
  { emoji: '🧁', name: 'cupcake', category: 'food' },
  { emoji: '🥧', name: 'pie', category: 'food' },
  { emoji: '🍫', name: 'chocolate bar', category: 'food' },
  { emoji: '🍬', name: 'candy', category: 'food' },
  { emoji: '🍭', name: 'lollipop', category: 'food' },

  // Objects & Shopping (~35 emojis)
  { emoji: '🛒', name: 'shopping cart', category: 'objects' },
  { emoji: '🛍️', name: 'shopping bags', category: 'objects' },
  { emoji: '📝', name: 'memo note', category: 'objects' },
  { emoji: '📋', name: 'clipboard list', category: 'objects' },
  { emoji: '📦', name: 'package box', category: 'objects' },
  { emoji: '🎁', name: 'gift present', category: 'objects' },
  { emoji: '💳', name: 'credit card', category: 'objects' },
  { emoji: '💵', name: 'money dollar', category: 'objects' },
  { emoji: '🏷️', name: 'label tag price', category: 'objects' },
  { emoji: '🧴', name: 'lotion bottle', category: 'objects' },
  { emoji: '🧼', name: 'soap bar', category: 'objects' },
  { emoji: '🧽', name: 'sponge', category: 'objects' },
  { emoji: '🧹', name: 'broom', category: 'objects' },
  { emoji: '🧺', name: 'basket laundry', category: 'objects' },
  { emoji: '🧻', name: 'toilet paper roll', category: 'objects' },
  { emoji: '🪥', name: 'toothbrush', category: 'objects' },
  { emoji: '🪒', name: 'razor', category: 'objects' },
  { emoji: '💊', name: 'pill medicine', category: 'objects' },
  { emoji: '🩹', name: 'bandage', category: 'objects' },
  { emoji: '🔋', name: 'battery', category: 'objects' },
  { emoji: '💡', name: 'light bulb idea', category: 'objects' },
  { emoji: '🔌', name: 'electric plug', category: 'objects' },
  { emoji: '📱', name: 'phone mobile', category: 'objects' },
  { emoji: '💻', name: 'laptop computer', category: 'objects' },
  { emoji: '🎧', name: 'headphones', category: 'objects' },
  { emoji: '📚', name: 'books', category: 'objects' },
  { emoji: '✏️', name: 'pencil', category: 'objects' },
  { emoji: '🖊️', name: 'pen', category: 'objects' },
  { emoji: '🔑', name: 'key', category: 'objects' },
  { emoji: '🔧', name: 'wrench tool', category: 'objects' },
  { emoji: '🔨', name: 'hammer', category: 'objects' },
  { emoji: '👕', name: 'shirt tshirt', category: 'objects' },
  { emoji: '👖', name: 'jeans pants', category: 'objects' },
  { emoji: '👟', name: 'shoes sneaker', category: 'objects' },
  { emoji: '🧦', name: 'socks', category: 'objects' },

  // Faces & People (~30 emojis)
  { emoji: '😀', name: 'grinning face', category: 'faces' },
  { emoji: '😊', name: 'smiling face happy', category: 'faces' },
  { emoji: '😍', name: 'heart eyes love', category: 'faces' },
  { emoji: '🥰', name: 'smiling hearts', category: 'faces' },
  { emoji: '😋', name: 'yummy delicious', category: 'faces' },
  { emoji: '🤤', name: 'drooling', category: 'faces' },
  { emoji: '😎', name: 'cool sunglasses', category: 'faces' },
  { emoji: '🤩', name: 'star struck', category: 'faces' },
  { emoji: '🥳', name: 'party celebration', category: 'faces' },
  { emoji: '😇', name: 'angel innocent', category: 'faces' },
  { emoji: '🤔', name: 'thinking', category: 'faces' },
  { emoji: '🧐', name: 'monocle curious', category: 'faces' },
  { emoji: '😴', name: 'sleeping', category: 'faces' },
  { emoji: '🤒', name: 'sick thermometer', category: 'faces' },
  { emoji: '🤢', name: 'nauseous', category: 'faces' },
  { emoji: '🥴', name: 'woozy', category: 'faces' },
  { emoji: '😱', name: 'screaming scared', category: 'faces' },
  { emoji: '😤', name: 'frustrated huffing', category: 'faces' },
  { emoji: '👶', name: 'baby', category: 'faces' },
  { emoji: '👧', name: 'girl', category: 'faces' },
  { emoji: '👦', name: 'boy', category: 'faces' },
  { emoji: '👩', name: 'woman', category: 'faces' },
  { emoji: '👨', name: 'man', category: 'faces' },
  { emoji: '👴', name: 'old man grandpa', category: 'faces' },
  { emoji: '👵', name: 'old woman grandma', category: 'faces' },
  { emoji: '👨‍🍳', name: 'chef cook man', category: 'faces' },
  { emoji: '👩‍🍳', name: 'chef cook woman', category: 'faces' },
  { emoji: '👪', name: 'family', category: 'faces' },
  { emoji: '🤝', name: 'handshake', category: 'faces' },
  { emoji: '👍', name: 'thumbs up', category: 'faces' },

  // Animals & Nature (~25 emojis)
  { emoji: '🐱', name: 'cat face', category: 'animals' },
  { emoji: '🐶', name: 'dog face', category: 'animals' },
  { emoji: '🐭', name: 'mouse face', category: 'animals' },
  { emoji: '🐹', name: 'hamster', category: 'animals' },
  { emoji: '🐰', name: 'rabbit bunny', category: 'animals' },
  { emoji: '🦊', name: 'fox', category: 'animals' },
  { emoji: '🐻', name: 'bear', category: 'animals' },
  { emoji: '🐼', name: 'panda', category: 'animals' },
  { emoji: '🐨', name: 'koala', category: 'animals' },
  { emoji: '🐷', name: 'pig face', category: 'animals' },
  { emoji: '🐮', name: 'cow face', category: 'animals' },
  { emoji: '🐔', name: 'chicken', category: 'animals' },
  { emoji: '🐣', name: 'chick hatching', category: 'animals' },
  { emoji: '🦆', name: 'duck', category: 'animals' },
  { emoji: '🐸', name: 'frog', category: 'animals' },
  { emoji: '🐝', name: 'bee honeybee', category: 'animals' },
  { emoji: '🦋', name: 'butterfly', category: 'animals' },
  { emoji: '🌸', name: 'cherry blossom', category: 'animals' },
  { emoji: '🌺', name: 'hibiscus flower', category: 'animals' },
  { emoji: '🌻', name: 'sunflower', category: 'animals' },
  { emoji: '🌹', name: 'rose', category: 'animals' },
  { emoji: '🌲', name: 'evergreen tree', category: 'animals' },
  { emoji: '🌴', name: 'palm tree', category: 'animals' },
  { emoji: '🍀', name: 'four leaf clover lucky', category: 'animals' },
  { emoji: '🌈', name: 'rainbow', category: 'animals' },

  // Activities (~20 emojis)
  { emoji: '⚽', name: 'soccer ball football', category: 'activities' },
  { emoji: '🏀', name: 'basketball', category: 'activities' },
  { emoji: '🏈', name: 'american football', category: 'activities' },
  { emoji: '⚾', name: 'baseball', category: 'activities' },
  { emoji: '🎾', name: 'tennis', category: 'activities' },
  { emoji: '🏐', name: 'volleyball', category: 'activities' },
  { emoji: '🎱', name: 'pool billiards', category: 'activities' },
  { emoji: '🏓', name: 'ping pong', category: 'activities' },
  { emoji: '🎳', name: 'bowling', category: 'activities' },
  { emoji: '🎯', name: 'bullseye target', category: 'activities' },
  { emoji: '🎮', name: 'video game controller', category: 'activities' },
  { emoji: '🎲', name: 'dice game', category: 'activities' },
  { emoji: '🎨', name: 'art palette', category: 'activities' },
  { emoji: '🎬', name: 'movie clapper', category: 'activities' },
  { emoji: '🎤', name: 'microphone karaoke', category: 'activities' },
  { emoji: '🎸', name: 'guitar', category: 'activities' },
  { emoji: '🎹', name: 'piano keyboard', category: 'activities' },
  { emoji: '🎺', name: 'trumpet', category: 'activities' },
  { emoji: '🏆', name: 'trophy winner', category: 'activities' },
  { emoji: '🥇', name: 'gold medal first', category: 'activities' },

  // Travel & Places (~20 emojis)
  { emoji: '✈️', name: 'airplane', category: 'travel' },
  { emoji: '🚗', name: 'car automobile', category: 'travel' },
  { emoji: '🚕', name: 'taxi cab', category: 'travel' },
  { emoji: '🚌', name: 'bus', category: 'travel' },
  { emoji: '🚂', name: 'train locomotive', category: 'travel' },
  { emoji: '🚢', name: 'ship boat', category: 'travel' },
  { emoji: '🚀', name: 'rocket spaceship', category: 'travel' },
  { emoji: '🏠', name: 'house home', category: 'travel' },
  { emoji: '🏢', name: 'office building', category: 'travel' },
  { emoji: '🏥', name: 'hospital', category: 'travel' },
  { emoji: '🏪', name: 'convenience store shop', category: 'travel' },
  { emoji: '🏬', name: 'department store mall', category: 'travel' },
  { emoji: '🏨', name: 'hotel', category: 'travel' },
  { emoji: '🏖️', name: 'beach umbrella', category: 'travel' },
  { emoji: '🏔️', name: 'mountain snow', category: 'travel' },
  { emoji: '🗽', name: 'statue liberty', category: 'travel' },
  { emoji: '🗼', name: 'tokyo tower', category: 'travel' },
  { emoji: '🌍', name: 'globe earth world', category: 'travel' },
  { emoji: '🌙', name: 'moon crescent', category: 'travel' },
  { emoji: '☀️', name: 'sun sunny', category: 'travel' },

  // Symbols (~20 emojis)
  { emoji: '❤️', name: 'red heart love', category: 'symbols' },
  { emoji: '🧡', name: 'orange heart', category: 'symbols' },
  { emoji: '💛', name: 'yellow heart', category: 'symbols' },
  { emoji: '💚', name: 'green heart', category: 'symbols' },
  { emoji: '💙', name: 'blue heart', category: 'symbols' },
  { emoji: '💜', name: 'purple heart', category: 'symbols' },
  { emoji: '⭐', name: 'star', category: 'symbols' },
  { emoji: '✨', name: 'sparkles', category: 'symbols' },
  { emoji: '💯', name: 'hundred perfect', category: 'symbols' },
  { emoji: '✅', name: 'check mark done', category: 'symbols' },
  { emoji: '❌', name: 'cross mark', category: 'symbols' },
  { emoji: '⚠️', name: 'warning', category: 'symbols' },
  { emoji: '🔥', name: 'fire hot', category: 'symbols' },
  { emoji: '💧', name: 'water droplet', category: 'symbols' },
  { emoji: '♻️', name: 'recycle', category: 'symbols' },
  { emoji: '🔔', name: 'bell notification', category: 'symbols' },
  { emoji: '🎵', name: 'music note', category: 'symbols' },
  { emoji: '💬', name: 'speech bubble chat', category: 'symbols' },
  { emoji: '❓', name: 'question mark', category: 'symbols' },
  { emoji: '❗', name: 'exclamation mark', category: 'symbols' },
];

export const CATEGORIES = [
  { id: 'food', icon: '🍕', label: 'Food & Drink' },
  { id: 'objects', icon: '🛒', label: 'Objects & Shopping' },
  { id: 'faces', icon: '😊', label: 'Faces & People' },
  { id: 'animals', icon: '🐱', label: 'Animals & Nature' },
  { id: 'activities', icon: '⚽', label: 'Activities' },
  { id: 'travel', icon: '✈️', label: 'Travel & Places' },
  { id: 'symbols', icon: '💡', label: 'Symbols' },
];
