import SwiftUI

/// A comprehensive emoji picker with categories, search, and scrollable grids.
struct EmojiPickerView: View {
    @Binding var selectedEmoji: String?
    @Environment(\.dismiss) private var dismiss
    
    @State private var searchQuery = ""
    
    private let columns = Array(repeating: GridItem(.flexible(), spacing: 8), count: 7)
    
    private var filteredCategories: [(name: String, emojis: [String])] {
        if searchQuery.isEmpty {
            return EmojiData.categories
        }
        let query = searchQuery.lowercased()
        return EmojiData.categories.compactMap { category in
            let filtered = category.emojis.filter { emoji in
                if let kw = EmojiData.keywords[emoji], kw.contains(query) {
                    return true
                }
                return category.name.lowercased().contains(query)
            }
            return filtered.isEmpty ? nil : (category.name, filtered)
        }
    }
    
    var body: some View {
        NavigationStack {
            ScrollView {
                LazyVStack(alignment: .leading, spacing: 20) {
                    ForEach(filteredCategories, id: \.name) { category in
                        VStack(alignment: .leading, spacing: 8) {
                            Text(category.name)
                                .font(.headline)
                                .foregroundStyle(.secondary)
                                .padding(.horizontal)
                            
                            LazyVGrid(columns: columns, spacing: 8) {
                                ForEach(category.emojis, id: \.self) { emoji in
                                    Button {
                                        selectedEmoji = emoji
                                        dismiss()
                                    } label: {
                                        Text(emoji)
                                            .font(.system(size: 28))
                                            .frame(width: 44, height: 44)
                                            .background(
                                                selectedEmoji == emoji
                                                    ? Color.accentColor.opacity(0.2)
                                                    : Color.clear
                                            )
                                            .clipShape(RoundedRectangle(cornerRadius: 8))
                                    }
                                    .buttonStyle(.plain)
                                }
                            }
                            .padding(.horizontal)
                        }
                    }
                    
                    if filteredCategories.isEmpty {
                        Text("No emojis match your search")
                            .foregroundStyle(.secondary)
                            .frame(maxWidth: .infinity, alignment: .center)
                            .padding(.vertical, 40)
                    }
                }
                .padding(.vertical)
            }
            .searchable(text: $searchQuery, prompt: "Search emojis")
            .navigationTitle("Choose Emoji")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .primaryAction) {
                    if selectedEmoji != nil {
                        Button("Clear") {
                            selectedEmoji = nil
                            dismiss()
                        }
                    }
                }
            }
        }
    }
}

/// Static emoji data organized by category.
private enum EmojiData {
    static let keywords: [String: String] = [
        // Smileys & People
        "😀": "grinning face happy smile",
        "😃": "grinning face big eyes happy smile",
        "😄": "grinning face smiling eyes happy",
        "😁": "beaming face smiling eyes grin happy",
        "😆": "grinning squinting face laugh happy",
        "😅": "grinning face sweat nervous happy",
        "🤣": "rolling floor laughing rofl lol",
        "😂": "face tears joy laughing crying lol",
        "🙂": "slightly smiling face happy",
        "🙃": "upside down face silly",
        "😉": "winking face wink flirt",
        "😊": "smiling face smiling eyes happy blush",
        "😇": "smiling face halo angel innocent",
        "🥰": "smiling face hearts love",
        "😍": "smiling face heart eyes love",
        "🤩": "star struck excited amazed",
        "😘": "face blowing kiss love",
        "😗": "kissing face kiss",
        "☺️": "smiling face happy content",
        "😚": "kissing face closed eyes kiss",
        "😙": "kissing face smiling eyes kiss",
        "🥲": "smiling face tear happy sad",
        "😋": "face savoring food yummy delicious",
        "😛": "face tongue stuck out playful",
        "😜": "winking face tongue silly playful",
        "🤪": "zany face crazy silly wild",
        "😝": "squinting face tongue playful",
        "🤑": "money mouth face rich dollar",
        "🤗": "hugging face hug embrace",
        "🤭": "face hand over mouth giggle oops",
        "🤫": "shushing face quiet secret",
        "🤔": "thinking face hmm wonder ponder",
        "🤐": "zipper mouth face secret quiet",
        "🤨": "face raised eyebrow skeptical",
        "😐": "neutral face meh blank",
        "😑": "expressionless face blank meh",
        "😶": "face without mouth silent speechless",
        "😏": "smirking face smug flirt",
        "😒": "unamused face annoyed bored",
        "🙄": "face rolling eyes annoyed whatever",
        "😬": "grimacing face awkward nervous",
        "😮‍💨": "face exhaling sigh relief",
        "🤥": "lying face pinocchio nose",
        "😌": "relieved face peaceful calm",
        "😔": "pensive face sad thoughtful",
        "😪": "sleepy face tired",
        "🤤": "drooling face hungry yummy",
        "😴": "sleeping face zzz tired sleep",
        "😷": "face medical mask sick",
        "🤒": "face thermometer sick fever",
        "🤕": "face bandage hurt injured",
        "🤢": "nauseated face sick gross",
        "🤮": "face vomiting sick throw up",
        "🤧": "sneezing face sick achoo",
        "🥵": "hot face heat sweating",
        "🥶": "cold face freezing frozen",
        "🥴": "woozy face dizzy drunk",
        "😵": "face spiral eyes dizzy",
        "🤯": "exploding head mind blown shocked",
        "🤠": "cowboy hat face western",
        "🥳": "partying face celebration birthday",
        "🥸": "disguised face glasses nose",
        "😎": "smiling face sunglasses cool",
        "🤓": "nerd face glasses smart",
        "🧐": "face monocle curious fancy",
        // Food & Drink
        "🍎": "red apple fruit food",
        "🍐": "pear fruit food green",
        "🍊": "tangerine orange fruit citrus",
        "🍋": "lemon citrus fruit yellow sour",
        "🍌": "banana fruit yellow",
        "🍉": "watermelon fruit summer",
        "🍇": "grapes fruit purple",
        "🍓": "strawberry fruit red berry",
        "🫐": "blueberries fruit berry blue",
        "🍈": "melon fruit cantaloupe",
        "🍒": "cherries fruit red",
        "🍑": "peach fruit",
        "🥭": "mango fruit tropical",
        "🍍": "pineapple fruit tropical",
        "🥥": "coconut fruit tropical",
        "🥝": "kiwi fruit green",
        "🍅": "tomato vegetable red",
        "🫒": "olive green food",
        "🥑": "avocado fruit green",
        "🍆": "eggplant vegetable purple",
        "🥔": "potato vegetable",
        "🥕": "carrot vegetable orange",
        "🌽": "corn vegetable yellow",
        "🌶️": "hot pepper spicy chili",
        "🫑": "bell pepper vegetable",
        "🥒": "cucumber vegetable green",
        "🥬": "leafy green vegetable lettuce",
        "🥦": "broccoli vegetable green",
        "🧄": "garlic vegetable",
        "🧅": "onion vegetable",
        "🥜": "peanuts nuts snack",
        "🫘": "beans legume",
        "🌰": "chestnut nut",
        "🍞": "bread food loaf",
        "🥐": "croissant bread pastry french",
        "🥖": "baguette bread french",
        "🫓": "flatbread pita naan",
        "🥨": "pretzel snack",
        "🥯": "bagel bread breakfast",
        "🥞": "pancakes breakfast stack",
        "🧇": "waffle breakfast",
        "🧀": "cheese wedge dairy",
        "🍖": "meat bone food",
        "🍗": "poultry leg chicken",
        "🥩": "cut meat steak beef",
        "🥓": "bacon meat breakfast",
        "🍔": "hamburger burger food",
        "🍟": "french fries food",
        "🍕": "pizza food slice",
        "🌭": "hot dog food",
        "🥪": "sandwich food lunch",
        "🌮": "taco mexican food",
        "🌯": "burrito mexican food wrap",
        "🫔": "tamale mexican food",
        "🥙": "stuffed flatbread pita gyro",
        "🧆": "falafel food middle eastern",
        "🥚": "egg food breakfast",
        "🍳": "cooking egg fried breakfast",
        "🥘": "shallow pan food paella",
        "🍲": "pot food stew soup",
        "🫕": "fondue cheese food",
        "🥣": "bowl spoon cereal oatmeal",
        "🥗": "green salad food healthy",
        "🍿": "popcorn snack movie",
        "🧈": "butter dairy",
        "🧂": "salt seasoning",
        "🥫": "canned food",
        "🍱": "bento box japanese food",
        "🍘": "rice cracker japanese",
        "🍙": "rice ball onigiri japanese",
        "🍚": "cooked rice food",
        "🍛": "curry rice food",
        "🍜": "steaming bowl noodles ramen",
        "🍝": "spaghetti pasta italian",
        "🍠": "roasted sweet potato",
        "🍢": "oden japanese food",
        "🍣": "sushi japanese food fish",
        "🍤": "fried shrimp tempura",
        "🍥": "fish cake narutomaki",
        "🥮": "moon cake chinese",
        "🍡": "dango japanese dessert",
        "🥟": "dumpling chinese food",
        "🥠": "fortune cookie chinese",
        "🥡": "takeout box food",
        "🦀": "crab seafood",
        "🦞": "lobster seafood",
        "🦐": "shrimp prawn seafood",
        "🦑": "squid seafood calamari",
        "🦪": "oyster seafood shell",
        "🍦": "soft ice cream dessert",
        "🍧": "shaved ice dessert",
        "🍨": "ice cream dessert",
        "🍩": "doughnut donut dessert",
        "🍪": "cookie dessert",
        "🎂": "birthday cake dessert",
        "🍰": "shortcake dessert cake",
        "🧁": "cupcake dessert",
        "🥧": "pie dessert",
        "🍫": "chocolate bar candy",
        "🍬": "candy sweet",
        "🍭": "lollipop candy",
        "🍮": "custard flan dessert",
        "🍯": "honey pot sweet",
        "🍼": "baby bottle milk",
        "🥛": "glass milk dairy",
        "☕": "hot beverage coffee tea",
        "🫖": "teapot tea",
        "🍵": "teacup tea green",
        "🍶": "sake japanese drink",
        "🍾": "bottle popping cork champagne",
        "🍷": "wine glass drink alcohol",
        "🍸": "cocktail glass martini drink",
        "🍹": "tropical drink cocktail",
        "🍺": "beer mug drink alcohol",
        "🍻": "clinking beer mugs cheers",
        "🥂": "clinking glasses champagne toast",
        "🥃": "tumbler glass whiskey drink",
        "🫗": "pouring liquid drink",
        "🥤": "cup straw soda drink",
        "🧋": "bubble tea boba drink",
        "🧃": "beverage box juice",
        "🧉": "mate drink",
        "🧊": "ice cube cold",
        // Animals & Nature
        "🐶": "dog face puppy pet animal",
        "🐱": "cat face kitty pet animal",
        "🐭": "mouse face rodent animal",
        "🐹": "hamster face pet animal",
        "🐰": "rabbit face bunny animal",
        "🦊": "fox face animal",
        "🐻": "bear face animal",
        "🐼": "panda face animal",
        "🐨": "koala face animal",
        "🐯": "tiger face animal",
        "🦁": "lion face animal king",
        "🐮": "cow face animal",
        "🐷": "pig face animal",
        "🐸": "frog face animal",
        "🐵": "monkey face animal",
        "🐔": "chicken bird animal",
        "🐧": "penguin bird animal",
        "🐦": "bird animal",
        "🐤": "baby chick bird animal",
        "🦆": "duck bird animal",
        "🦅": "eagle bird animal",
        "🦉": "owl bird animal night",
        "🦇": "bat animal night",
        "🐺": "wolf face animal",
        "🐗": "boar animal pig wild",
        "🐴": "horse face animal",
        "🦄": "unicorn fantasy horse",
        "🐝": "honeybee bee insect",
        "🪱": "worm insect",
        "🐛": "bug caterpillar insect",
        "🦋": "butterfly insect",
        "🐌": "snail slow",
        "🐞": "lady beetle ladybug insect",
        "🐜": "ant insect",
        "🪰": "fly insect",
        "🪲": "beetle insect",
        "🪳": "cockroach insect bug",
        "🦟": "mosquito insect bug",
        "🦗": "cricket insect",
        "🕷️": "spider insect web",
        "🦂": "scorpion",
        "🐢": "turtle reptile slow",
        "🐍": "snake reptile",
        "🦎": "lizard reptile",
        "🦖": "t-rex dinosaur",
        "🦕": "sauropod dinosaur",
        "🐙": "octopus sea",
        "🐡": "blowfish puffer fish",
        "🐠": "tropical fish",
        "🐟": "fish",
        "🐬": "dolphin sea mammal",
        "🐳": "spouting whale sea",
        "🐋": "whale sea mammal",
        "🦈": "shark fish sea",
        "🦭": "seal sea mammal",
        "🐊": "crocodile alligator reptile",
        "🐅": "tiger animal",
        "🐆": "leopard animal cat",
        "🦓": "zebra animal",
        "🦍": "gorilla ape animal",
        "🦧": "orangutan ape animal",
        "🐘": "elephant animal",
        "🦛": "hippopotamus hippo animal",
        "🦏": "rhinoceros rhino animal",
        "🐪": "camel animal desert",
        "🐫": "two hump camel bactrian",
        "🦒": "giraffe animal tall",
        "🦘": "kangaroo animal australia",
        "🦬": "bison buffalo animal",
        "🐃": "water buffalo animal",
        "🐂": "ox animal",
        "🐄": "cow animal",
        "🐎": "horse animal",
        "🐖": "pig animal",
        "🐏": "ram sheep animal",
        "🐑": "ewe sheep animal",
        "🦙": "llama alpaca animal",
        "🐐": "goat animal",
        "🦌": "deer animal",
        "🐕": "dog animal pet",
        "🐩": "poodle dog animal pet",
        "🦮": "guide dog service animal",
        "🐈": "cat animal pet",
        "🐓": "rooster chicken bird",
        "🦃": "turkey bird animal",
        "🦤": "dodo bird extinct",
        "🦚": "peacock bird animal",
        "🦜": "parrot bird animal",
        "🦢": "swan bird animal",
        "🦩": "flamingo bird animal pink",
        "🕊️": "dove bird peace",
        "🐇": "rabbit bunny animal",
        "🦝": "raccoon animal",
        "🦨": "skunk animal",
        "🦡": "badger animal",
        "🦫": "beaver animal",
        "🦦": "otter animal",
        "🦥": "sloth animal slow",
        "🐁": "mouse rodent animal",
        "🐀": "rat rodent animal",
        "🐿️": "chipmunk squirrel animal",
        "🦔": "hedgehog animal",
        "🐾": "paw prints animal feet",
        "🌸": "cherry blossom flower pink",
        "🌺": "hibiscus flower",
        "🌻": "sunflower flower yellow",
        "🌹": "rose flower red love",
        "🌷": "tulip flower",
        "🌼": "blossom flower",
        "🪻": "hyacinth flower purple",
        "🪷": "lotus flower",
        "🌱": "seedling plant sprout",
        "🌲": "evergreen tree pine",
        "🌳": "deciduous tree",
        "🌴": "palm tree tropical",
        "🌵": "cactus desert plant",
        "🍀": "four leaf clover luck",
        "☘️": "shamrock clover irish",
        "🍃": "leaf fluttering wind",
        "🍂": "fallen leaf autumn",
        "🍁": "maple leaf fall canada",
        // Objects
        "📱": "mobile phone smartphone iphone",
        "💻": "laptop computer macbook",
        "🖥️": "desktop computer monitor screen",
        "🖨️": "printer",
        "⌨️": "keyboard computer",
        "🖱️": "computer mouse",
        "🖲️": "trackball",
        "💽": "computer disk minidisc",
        "💾": "floppy disk save",
        "💿": "optical disk cd dvd",
        "📀": "dvd disk",
        "📼": "videocassette vhs tape",
        "📷": "camera photo",
        "📸": "camera flash photo",
        "📹": "video camera",
        "🎥": "movie camera film",
        "📽️": "film projector movie",
        "🎞️": "film frames movie",
        "📞": "telephone receiver phone call",
        "☎️": "telephone phone call",
        "📟": "pager",
        "📠": "fax machine",
        "📺": "television tv screen",
        "📻": "radio",
        "🎙️": "studio microphone podcast",
        "🎚️": "level slider audio",
        "🎛️": "control knobs audio",
        "🧭": "compass navigation direction",
        "⏱️": "stopwatch timer",
        "⏲️": "timer clock",
        "⏰": "alarm clock wake",
        "🕰️": "mantelpiece clock time",
        "⌛": "hourglass done time",
        "⏳": "hourglass flowing time sand",
        "📡": "satellite antenna signal",
        "🔋": "battery power",
        "🔌": "electric plug power",
        "💡": "light bulb idea",
        "🔦": "flashlight torch light",
        "🕯️": "candle light",
        "🧯": "fire extinguisher safety",
        "🛒": "shopping cart trolley",
        "🛍️": "shopping bags",
        "📦": "package box delivery",
        "📮": "postbox mailbox",
        "📫": "closed mailbox raised flag",
        "📪": "closed mailbox lowered flag",
        "📬": "open mailbox raised flag",
        "📭": "open mailbox lowered flag",
        "📨": "incoming envelope mail",
        "📧": "e-mail email",
        "💌": "love letter mail heart",
        "📥": "inbox tray",
        "📤": "outbox tray",
        "📜": "scroll document",
        "📃": "page curl document",
        "📄": "page facing up document",
        "📑": "bookmark tabs document",
        "🧾": "receipt document",
        "📊": "bar chart graph",
        "📈": "chart increasing graph up",
        "📉": "chart decreasing graph down",
        "🗒️": "spiral notepad",
        "🗓️": "spiral calendar",
        "📆": "tear off calendar date",
        "📅": "calendar date",
        "🗑️": "wastebasket trash delete",
        "📇": "card index",
        "🗃️": "card file box",
        "🗳️": "ballot box vote",
        "🗄️": "file cabinet storage",
        "📋": "clipboard document",
        "📁": "file folder directory",
        "📂": "open file folder directory",
        "🗂️": "card index dividers",
        "🗞️": "rolled newspaper news",
        "📰": "newspaper news",
        "📓": "notebook",
        "📔": "notebook decorative cover",
        "📒": "ledger notebook",
        "📕": "closed book red",
        "📗": "green book",
        "📘": "blue book",
        "📙": "orange book",
        "📚": "books stack reading",
        "📖": "open book reading",
        "🔖": "bookmark",
        "🧷": "safety pin",
        "🔗": "link chain",
        "📎": "paperclip attach",
        "🖇️": "linked paperclips attach",
        "📐": "triangular ruler",
        "📏": "straight ruler measure",
        "🧮": "abacus calculate",
        "📌": "pushpin pin",
        "📍": "round pushpin location pin",
        "✂️": "scissors cut",
        "🖊️": "pen write",
        "🖋️": "fountain pen write",
        "✒️": "black nib pen write",
        "🖌️": "paintbrush art",
        "🖍️": "crayon art draw",
        "📝": "memo note write",
        "✏️": "pencil write draw",
        "🔍": "magnifying glass left search",
        "🔎": "magnifying glass right search",
        "🔏": "locked pen",
        "🔐": "locked key",
        "🔒": "locked secure",
        "🔓": "unlocked open",
        // Travel & Places
        "🏠": "house home building",
        "🏡": "house garden home",
        "🏢": "office building",
        "🏣": "japanese post office",
        "🏤": "post office building",
        "🏥": "hospital building medical",
        "🏦": "bank building money",
        "🏨": "hotel building",
        "🏩": "love hotel building",
        "🏪": "convenience store building shop",
        "🏫": "school building education",
        "🏬": "department store building shop",
        "🏭": "factory building industrial",
        "🏯": "japanese castle building",
        "🏰": "castle building medieval",
        "💒": "wedding church building",
        "🗼": "tokyo tower",
        "🗽": "statue liberty new york",
        "⛪": "church building religion",
        "🕌": "mosque building religion",
        "🛕": "hindu temple building",
        "🕍": "synagogue building religion",
        "⛩️": "shinto shrine japan",
        "🕋": "kaaba mecca islam",
        "⛲": "fountain water",
        "⛺": "tent camping outdoor",
        "🌁": "foggy bridge san francisco",
        "🌃": "night stars city",
        "🏙️": "cityscape buildings skyline",
        "🌄": "sunrise mountains",
        "🌅": "sunrise sun ocean",
        "🌆": "cityscape dusk evening",
        "🌇": "sunset city",
        "🌉": "bridge night",
        "♨️": "hot springs spa",
        "🎠": "carousel horse playground",
        "🛝": "playground slide",
        "🎡": "ferris wheel amusement",
        "🎢": "roller coaster amusement",
        "💈": "barber pole",
        "🎪": "circus tent",
        "🚂": "locomotive train steam",
        "🚃": "railway car train",
        "🚄": "high speed train bullet",
        "🚅": "bullet train",
        "🚆": "train",
        "🚇": "metro subway underground",
        "🚈": "light rail train",
        "🚉": "station train",
        "🚊": "tram streetcar",
        "🚝": "monorail train",
        "🚞": "mountain railway train",
        "🚋": "tram car streetcar",
        "🚌": "bus public transport",
        "🚍": "oncoming bus",
        "🚎": "trolleybus",
        "🚐": "minibus van",
        "🚑": "ambulance emergency medical",
        "🚒": "fire engine truck",
        "🚓": "police car",
        "🚔": "oncoming police car",
        "🚕": "taxi cab",
        "🚖": "oncoming taxi cab",
        "🚗": "automobile car",
        "🚘": "oncoming automobile car",
        "🚙": "sport utility vehicle suv",
        "🛻": "pickup truck",
        "🚚": "delivery truck",
        "🚛": "articulated lorry semi truck",
        "🚜": "tractor farm",
        "🏎️": "racing car formula",
        "🏍️": "motorcycle bike",
        "🛵": "motor scooter",
        "🛺": "auto rickshaw tuk tuk",
        "🚲": "bicycle bike",
        "🛴": "kick scooter",
        "🛹": "skateboard",
        "🛼": "roller skate",
        "🚏": "bus stop",
        "🛣️": "motorway highway road",
        "🛤️": "railway track train",
        "🛢️": "oil drum barrel",
        "⛽": "fuel pump gas station",
        "🚨": "police car light emergency",
        "🚥": "horizontal traffic light",
        "🚦": "vertical traffic light",
        "🛑": "stop sign",
        "🚧": "construction warning",
        "⚓": "anchor ship nautical",
        "🛟": "ring buoy life preserver",
        "⛵": "sailboat boat",
        "🛶": "canoe boat",
        "🚤": "speedboat boat",
        "🛳️": "passenger ship cruise",
        "⛴️": "ferry boat ship",
        "🛥️": "motor boat",
        "🚢": "ship boat",
        "✈️": "airplane flight plane travel",
        "🛩️": "small airplane plane",
        "🛫": "airplane departure takeoff",
        "🛬": "airplane arrival landing",
        "🪂": "parachute skydiving",
        "💺": "seat airplane chair",
        "🚁": "helicopter",
        "🚟": "suspension railway",
        "🚠": "mountain cableway",
        "🚡": "aerial tramway",
        "🛰️": "satellite space",
        "🚀": "rocket space launch",
        "🛸": "flying saucer ufo alien",
        // Activities
        "⚽": "soccer ball football sport",
        "🏀": "basketball sport",
        "🏈": "american football sport",
        "⚾": "baseball sport",
        "🥎": "softball sport",
        "🎾": "tennis sport",
        "🏐": "volleyball sport",
        "🏉": "rugby football sport",
        "🥏": "flying disc frisbee sport",
        "🎱": "pool 8 ball billiards",
        "🪀": "yo-yo toy",
        "🏓": "ping pong table tennis",
        "🏸": "badminton sport",
        "🏒": "ice hockey sport",
        "🏑": "field hockey sport",
        "🥍": "lacrosse sport",
        "🏏": "cricket game sport",
        "🪃": "boomerang",
        "🥅": "goal net sport",
        "⛳": "flag hole golf sport",
        "🪁": "kite flying",
        "🏹": "bow arrow archery",
        "🎣": "fishing pole rod",
        "🤿": "diving mask snorkel",
        "🥊": "boxing glove sport",
        "🥋": "martial arts uniform",
        "🎽": "running shirt sport",
        "🛷": "sled winter",
        "⛸️": "ice skate winter",
        "🥌": "curling stone winter",
        "🎿": "skis winter sport",
        "⛷️": "skier winter sport",
        "🏂": "snowboarder winter sport",
        "🏋️": "person lifting weights gym",
        "🤼": "people wrestling sport",
        "🤸": "person cartwheeling gymnastics",
        "⛹️": "person bouncing ball basketball",
        "🤺": "person fencing sport",
        "🤾": "person playing handball sport",
        "🏌️": "person golfing sport",
        "🏇": "horse racing sport",
        "🧘": "person lotus position yoga meditation",
        "🏄": "person surfing sport wave",
        "🏊": "person swimming sport",
        "🤽": "person playing water polo sport",
        "🚣": "person rowing boat",
        "🧗": "person climbing sport",
        "🚵": "person mountain biking sport",
        "🚴": "person biking cycling sport",
        "🏆": "trophy winner award",
        "🥇": "first place medal gold",
        "🥈": "second place medal silver",
        "🥉": "third place medal bronze",
        "🏅": "sports medal",
        "🎖️": "military medal",
        "🏵️": "rosette award",
        "🎗️": "reminder ribbon awareness",
        "🎫": "ticket admission",
        "🎟️": "admission tickets",
        "🤹": "person juggling circus",
        "🎭": "performing arts theater drama",
        "🩰": "ballet shoes dance",
        "🎨": "artist palette paint art",
        "🎬": "clapper board film movie",
        "🎤": "microphone karaoke sing",
        "🎧": "headphone music audio",
        "🎼": "musical score music notes",
        "🎹": "musical keyboard piano",
        "🥁": "drum music",
        "🪘": "long drum music",
        "🎷": "saxophone music jazz",
        "🎺": "trumpet music",
        "🎸": "guitar music",
        "🪕": "banjo music",
        "🎻": "violin music",
        "🪗": "accordion music",
        "🎲": "game die dice",
        "♟️": "chess pawn game",
        "🎯": "direct hit target bullseye darts",
        "🎳": "bowling sport",
        "🎮": "video game controller gaming",
        "🕹️": "joystick gaming arcade",
        "🎰": "slot machine gambling casino",
        // Symbols
        "❤️": "red heart love",
        "🧡": "orange heart love",
        "💛": "yellow heart love",
        "💚": "green heart love",
        "💙": "blue heart love",
        "💜": "purple heart love",
        "🖤": "black heart love",
        "🤍": "white heart love",
        "🤎": "brown heart love",
        "💔": "broken heart sad love",
        "❣️": "heart exclamation love",
        "💕": "two hearts love",
        "💞": "revolving hearts love",
        "💓": "beating heart love",
        "💗": "growing heart love",
        "💖": "sparkling heart love",
        "💘": "heart arrow love cupid",
        "💝": "heart ribbon gift love",
        "✨": "sparkles glitter magic",
        "⭐": "star",
        "🌟": "glowing star",
        "💫": "dizzy star",
        "🔥": "fire hot flame",
        "🎉": "party popper celebration",
        "🎊": "confetti ball celebration",
        "🎈": "balloon party",
        "🎁": "wrapped gift present",
        "🎀": "ribbon bow",
        "🎄": "christmas tree holiday",
        "🎃": "jack o lantern halloween pumpkin",
        "🎆": "fireworks celebration",
        "🎇": "sparkler fireworks",
        "✅": "check mark yes done",
        "❌": "cross mark no wrong",
        "⭕": "hollow red circle",
        "🚫": "prohibited no forbidden",
        "💯": "hundred points perfect score",
        "🔴": "red circle",
        "🟠": "orange circle",
        "🟡": "yellow circle",
        "🟢": "green circle",
        "🔵": "blue circle",
        "🟣": "purple circle",
        "⚫": "black circle",
        "⚪": "white circle",
        "🟤": "brown circle",
        "🔶": "large orange diamond",
        "🔷": "large blue diamond",
        "🔸": "small orange diamond",
        "🔹": "small blue diamond",
        "🔺": "red triangle pointed up",
        "🔻": "red triangle pointed down",
        "💠": "diamond with dot",
        "🔘": "radio button",
        "🏳️": "white flag",
        "🏴": "black flag",
        "🏁": "chequered flag racing finish",
        "🚩": "triangular flag red",
        "🔔": "bell notification alert",
        "🔕": "bell slash silent mute",
        "📣": "megaphone cheering",
        "📢": "loudspeaker announcement",
        "💬": "speech bubble chat talk",
        "💭": "thought bubble thinking",
        "🗯️": "anger bubble mad",
        "♠️": "spade suit cards",
        "♣️": "club suit cards",
        "♥️": "heart suit cards",
        "♦️": "diamond suit cards",
        "🃏": "joker card",
        "🎴": "flower playing cards",
        "🀄": "mahjong red dragon"
    ]
    
    static let categories: [(name: String, emojis: [String])] = [
        (
            "Smileys & People",
            ["😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃", "😉", "😊", "😇", "🥰", "😍", "🤩", "😘", "😗", "☺️", "😚", "😙", "🥲", "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗", "🤭", "🤫", "🤔", "🤐", "🤨", "😐", "😑", "😶", "😏", "😒", "🙄", "😬", "😮‍💨", "🤥", "😌", "😔", "😪", "🤤", "😴", "😷", "🤒", "🤕", "🤢", "🤮", "🤧", "🥵", "🥶", "🥴", "😵", "🤯", "🤠", "🥳", "🥸", "😎", "🤓", "🧐"]
        ),
        (
            "Food & Drink",
            ["🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐", "🍈", "🍒", "🍑", "🥭", "🍍", "🥥", "🥝", "🍅", "🫒", "🥑", "🍆", "🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦", "🧄", "🧅", "🥜", "🫘", "🌰", "🍞", "🥐", "🥖", "🫓", "🥨", "🥯", "🥞", "🧇", "🧀", "🍖", "🍗", "🥩", "🥓", "🍔", "🍟", "🍕", "🌭", "🥪", "🌮", "🌯", "🫔", "🥙", "🧆", "🥚", "🍳", "🥘", "🍲", "🫕", "🥣", "🥗", "🍿", "🧈", "🧂", "🥫", "🍱", "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍠", "🍢", "🍣", "🍤", "🍥", "🥮", "🍡", "🥟", "🥠", "🥡", "🦀", "🦞", "🦐", "🦑", "🦪", "🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫", "🍬", "🍭", "🍮", "🍯", "🍼", "🥛", "☕", "🫖", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂", "🥃", "🫗", "🥤", "🧋", "🧃", "🧉", "🧊"]
        ),
        (
            "Animals & Nature",
            ["🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐸", "🐵", "🐔", "🐧", "🐦", "🐤", "🦆", "🦅", "🦉", "🦇", "🐺", "🐗", "🐴", "🦄", "🐝", "🪱", "🐛", "🦋", "🐌", "🐞", "🐜", "🪰", "🪲", "🪳", "🦟", "🦗", "🕷️", "🦂", "🐢", "🐍", "🦎", "🦖", "🦕", "🐙", "🦑", "🦐", "🦀", "🐡", "🐠", "🐟", "🐬", "🐳", "🐋", "🦈", "🦭", "🐊", "🐅", "🐆", "🦓", "🦍", "🦧", "🐘", "🦛", "🦏", "🐪", "🐫", "🦒", "🦘", "🦬", "🐃", "🐂", "🐄", "🐎", "🐖", "🐏", "🐑", "🦙", "🐐", "🦌", "🐕", "🐩", "🦮", "🐈", "🐓", "🦃", "🦤", "🦚", "🦜", "🦢", "🦩", "🕊️", "🐇", "🦝", "🦨", "🦡", "🦫", "🦦", "🦥", "🐁", "🐀", "🐿️", "🦔", "🐾", "🌸", "🌺", "🌻", "🌹", "🌷", "🌼", "🪻", "🪷", "🌱", "🌲", "🌳", "🌴", "🌵", "🍀", "☘️", "🍃", "🍂", "🍁"]
        ),
        (
            "Objects",
            ["📱", "💻", "🖥️", "🖨️", "⌨️", "🖱️", "🖲️", "💽", "💾", "💿", "📀", "📼", "📷", "📸", "📹", "🎥", "📽️", "🎞️", "📞", "☎️", "📟", "📠", "📺", "📻", "🎙️", "🎚️", "🎛️", "🧭", "⏱️", "⏲️", "⏰", "🕰️", "⌛", "⏳", "📡", "🔋", "🔌", "💡", "🔦", "🕯️", "🧯", "🛒", "🛍️", "📦", "📮", "📫", "📪", "📬", "📭", "📨", "📧", "💌", "📥", "📤", "📜", "📃", "📄", "📑", "🧾", "📊", "📈", "📉", "🗒️", "🗓️", "📆", "📅", "🗑️", "📇", "🗃️", "🗳️", "🗄️", "📋", "📁", "📂", "🗂️", "🗞️", "📰", "📓", "📔", "📒", "📕", "📗", "📘", "📙", "📚", "📖", "🔖", "🧷", "🔗", "📎", "🖇️", "📐", "📏", "🧮", "📌", "📍", "✂️", "🖊️", "🖋️", "✒️", "🖌️", "🖍️", "📝", "✏️", "🔍", "🔎", "🔏", "🔐", "🔒", "🔓"]
        ),
        (
            "Travel & Places",
            ["🏠", "🏡", "🏢", "🏣", "🏤", "🏥", "🏦", "🏨", "🏩", "🏪", "🏫", "🏬", "🏭", "🏯", "🏰", "💒", "🗼", "🗽", "⛪", "🕌", "🛕", "🕍", "⛩️", "🕋", "⛲", "⛺", "🌁", "🌃", "🏙️", "🌄", "🌅", "🌆", "🌇", "🌉", "♨️", "🎠", "🛝", "🎡", "🎢", "💈", "🎪", "🚂", "🚃", "🚄", "🚅", "🚆", "🚇", "🚈", "🚉", "🚊", "🚝", "🚞", "🚋", "🚌", "🚍", "🚎", "🚐", "🚑", "🚒", "🚓", "🚔", "🚕", "🚖", "🚗", "🚘", "🚙", "🛻", "🚚", "🚛", "🚜", "🏎️", "🏍️", "🛵", "🛺", "🚲", "🛴", "🛹", "🛼", "🚏", "🛣️", "🛤️", "🛢️", "⛽", "🚨", "🚥", "🚦", "🛑", "🚧", "⚓", "🛟", "⛵", "🛶", "🚤", "🛳️", "⛴️", "🛥️", "🚢", "✈️", "🛩️", "🛫", "🛬", "🪂", "💺", "🚁", "🚟", "🚠", "🚡", "🛰️", "🚀", "🛸"]
        ),
        (
            "Activities",
            ["⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱", "🪀", "🏓", "🏸", "🏒", "🏑", "🥍", "🏏", "🪃", "🥅", "⛳", "🪁", "🏹", "🎣", "🤿", "🥊", "🥋", "🎽", "🛹", "🛼", "🛷", "⛸️", "🥌", "🎿", "⛷️", "🏂", "🪂", "🏋️", "🤼", "🤸", "⛹️", "🤺", "🤾", "🏌️", "🏇", "🧘", "🏄", "🏊", "🤽", "🚣", "🧗", "🚵", "🚴", "🏆", "🥇", "🥈", "🥉", "🏅", "🎖️", "🏵️", "🎗️", "🎫", "🎟️", "🎪", "🤹", "🎭", "🩰", "🎨", "🎬", "🎤", "🎧", "🎼", "🎹", "🥁", "🪘", "🎷", "🎺", "🎸", "🪕", "🎻", "🪗", "🎲", "♟️", "🎯", "🎳", "🎮", "🕹️", "🎰"]
        ),
        (
            "Symbols",
            ["❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❣️", "💕", "💞", "💓", "💗", "💖", "💘", "💝", "✨", "⭐", "🌟", "💫", "🔥", "🎉", "🎊", "🎈", "🎁", "🎀", "🎄", "🎃", "🎆", "🎇", "✅", "❌", "⭕", "🚫", "💯", "🔴", "🟠", "🟡", "🟢", "🔵", "🟣", "⚫", "⚪", "🟤", "🔶", "🔷", "🔸", "🔹", "🔺", "🔻", "💠", "🔘", "🏳️", "🏴", "🏁", "🚩", "🔔", "🔕", "📣", "📢", "💬", "💭", "🗯️", "♠️", "♣️", "♥️", "♦️", "🃏", "🎴", "🀄"]
        )
    ]
}

#Preview {
    EmojiPickerView(selectedEmoji: .constant("🍎"))
}
